### ISSUE TITLE
Sample module doesn't help promote good security in tblgatewaylog

### ISSUE THREAD

**Issue by jas8522** [WHMCS/sample-merchant-gateway#10]
Currently the return value for a capture (such as in the function `merchantgateway_capture`) shows as including the raw response from the payment gateway like this: ` 'rawdata' => $responseData,` at merchantgateway.php:287

That raw data is then dumped by WHMCS to tblgatewaylog.

Many gateways return a bunch of data so that the requesting system (in this case the gateway module) can validate the request. **This return data often includes the credit card number.** 

To ensure the sample module encourages best practices for storing of credit card data (as in, not storing credit card data inadvertently in this instance), and because it's not explicitly shown in the sample module that the 'rawdata' var in the array will be entirely stored in the gateway log, I believe the sample module should include something similar to what you see below. This will help indicate that the developer should use (and how best to use) proper security practices prior to passing the raw response data back to WHMCS for storage in the gateway log.

```
/*If the response data contains a credit card number (check the gateway API documentation to confirm), it's important to mask the credit card number before WHMCS inserts it unencrypted into the gateway log. Here's an example where the API returns an array key of 'CreditCardNumber': */
$responseData['CreditCardNumber'] = '****' . substr($responseData['CreditCardNumber'], -4);
```

I've also [posted a variation of this here](https://github.com/WHMCS/sample-gateway-module/issues/11), because it wasn't clear which sample module is the currentlly active one -- it *looks* like this one is more complete, so this seems to be the better spot to discuss things / report issues.

**Comment by mattpugh** [comment]
Hi there,

Thanks for taking the time to open an issue.

As I understand it, you are working with a payment gateway that is returning a full unmasked credit card number in the API response you receive to a payment request for capture.

I can't recall a time I've ever seen a payment gateway return sensitive information such as a full credit card number in plain text format. It would not only be very unusual to see something like this but also a significant security concern with the gateway itself. If you were to find a payment gateway API that was doing something like this, I would suggest contacting that gateway and reporting it to them as a security concern at the very least.

That said, if there is sensitive information contained within the response data, then masking it or removing it entirely would certainly be appropriate before passing it to logging. However from our experience, API response data containing sensitive data is rare and also very gateway specific, and that's why the sample code we provide does not cater to this at this time. We can consider adding some kind of inline note within the code, however, it would need to be something generic enough to make sense in all scenarios.

I will also add that it is always expected that our sample module code will be used in conjunction with our developer documentation where it is stated that any data returned will be logged (ref https://developers.whmcs.com/payment-gateways/merchant-gateway/).

Thanks,
Matt
